### ISSUE TITLE
Compute Canada Integration

### ISSUE THREAD

**Issue by Alex-A14** [brainhack-school2020/stong3_fMRI_processing#2]
Hi Frederic,

Do you know how you plan to integrate Compute Canada into Jupyter? Will you add terminal code in your notebook to access CC? Or process the data remotely and then import results for the final write-up?
Was going to ask @ltetrel about this

**Comment by ltetrel** [comment]
There are two ways of accessing notebooks on compute canada :
1. Using the CC jupyterhub as @cmd-ntrf mentionned during his talk from last week.
2. Launching dynamically a singularity container in your slurm script using `salloc`, by [port forwarding the compute node](https://docs.computecanada.ca/wiki/SSH_tunnelling) . Check here a tutorial on how it would work when you have a node avaiable : https://simexp-documentation.readthedocs.io/en/latest/tutorials/server_dl.html

**Comment by ltetrel** [comment]
I would not necessarily recommend to use notebooks on CC since it is not really meant for interactive jobs, and it could be difficult to setup if you are not familiar with HPC. I would advice you to use instead a basic `.py` file.

**Comment by ltetrel** [comment]
Just realized that CC doc describes how to do it (without singularity), so it could actually be easier to follow this :
https://docs.computecanada.ca/wiki/Jupyter#Starting_Jupyter_Notebook

**Comment by Alex-A14** [comment]
That's right, I had completely forgotten about interactive software inside Jupyterhub. Thanks!
